################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#   Copyright (c) 2019 Nokia.                                                  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################
rtmgr:
  imagePullPolicy: IfNotPresent
  image:
    name: ric-plt-rtmgr
    tag: 0.3.8
    registry: "nexus3.o-ran-sc.org:10002/o-ran-sc"
  
  rpe: rmrpush
  sbi: rmrpush
  sbiurl: 0.0.0.0
  nbi: httpRESTful
  nbiurl: http://0.0.0.0:8888

  # Service ports are now defined in 
  # ric-common/Common-Template/helm/ric-common/templates/_ports.tpl file.
  # If need to change a service port, make the code change necessary, then
  # update the _ports.tpl file with the new port number.
